#!/bin/bash

db="database.yt"

echo "-- downloading $db"
curl -sLO https://w3b.net/$db

start_time=$(head -1 $db | awk -F '"' '{print$4}')
now=$(date +"%s")
total=$(echo $(($now-$start_time)))
png="mark-hick.png"

echo "-- $db contains $(($total/3600)) hours data."

rrdtool create mark.rrd --step=1 --start=1548879240 \
    DS:ds1:GAUGE:5m:U:U RRA:AVERAGE:0:1:${total}s
rrdtool create hick.rrd --step=1 --start=1548879240 \
    DS:ds1:GAUGE:5m:U:U RRA:AVERAGE:0:1:${total}s

cat $db | grep Mark | \
    awk -v "rrdfile=mark.rrd" -F '"' \
    '{printf("rrdtool update %s %s:%s\n",rrdfile,$4,$8)}' >/tmp/rrdmark
cat $db | grep hickok | \
    awk -v "rrdfile=hick.rrd" -F '"' \
    '{printf("rrdtool update %s %s:%s\n",rrdfile,$4,$8)}' >/tmp/rrdhick

sh /tmp/rrdmark
sh /tmp/rrdhick

1>/dev/null rrdtool graph $png --start 1548879240 --end now \
    -w 600 -h 300 \
    DEF:ds1a=mark.rrd:ds1:AVERAGE \
    DEF:ds2a=hick.rrd:ds1:AVERAGE \
    LINE2:ds1a#40a060:"Mark Wiens" \
    LINE2:ds2a#ff4040:"Hickok45"

echo "-- $png has been created."

xdg-open $png
