#!/bin/bash

subscribers() {
    subscribers=$(wget -q --html-extension --restrict-file-names=windows \
        --domains youtube.com "$2" -O - | grep abonnees | \
        awk -F 'aria-label="' '{print$6}' | awk '{print$1}' | sed 's/\.//') && \
    echo "$subscribers $1"
}

subscribers "Mr Bald" https://www.youtube.com/channel/UCxDZs_ltFFvn0FDHT6kmoXA
subscribers "Karl Rock" https://www.youtube.com/channel/UCtfXgNnA-QcxjHJjk5wXLFg
