#!/bin/bash

### Mister Bald
./yt-subscribers https://www.youtube.com/channel/UCxDZs_ltFFvn0FDHT6kmoXA

### Karl Rock
./yt-subscribers https://www.youtube.com/channel/UCtfXgNnA-QcxjHJjk5wXLFg

### Mark Wiens
./yt-subscribers https://www.youtube.com/channel/UCyEd6QBSgat5kkC6svyjudA
