#!/bin/bash

subscribers() {
    channel=$(wget -q "$1" -O -| \
        grep '<title>') && \
    subscribers=$(wget -q "$1" -O - | grep abonnees | \
        awk -F 'aria-label="' '{print$6}' | awk '{print$1}' | sed 's/\.//g') && \
    time=$(date +"%s") && \
    echo -e "{\"time\":\"$time\",\"subscribers\":\"$subscribers\",\"channel\":\"${channel:9}\"}"
}

if [ "$#" -eq 0 ]; then
    mrbald="https://www.youtube.com/channel/UCxDZs_ltFFvn0FDHT6kmoXA"
    echo -e "\nUsage: $0 <youtube main channel page>\n"
    echo -e "For example: $0 $mrbald shows:\n"
    subscribers $mrbald
    echo
else
    subscribers "$1"
fi